on:
  workflow_dispatch:
  push:
    branches:
      - friendly
    paths-ignore:
      - '.github/workflows/auto-rebase.yaml'
  repository_dispatch:
    types:
      - nixos-unstable-rebase
name: Trigger nixpkgs-friendly-overlay
jobs:
  trigger-nixpkgs-friendly-overlay:
    environment: bot
    runs-on: ubuntu-latest
    steps:
      - name: Trigger nixpkgs-friendly-overlay repo
        env:
          TOKEN_BOT: ${{ secrets.TOKEN_BOT }}
        run: |
          curl -L -X POST \
            -H "Accept: application/vnd.github+json"  \
            -H "Authorization: Bearer $TOKEN_BOT" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d '{"event_type":"auto_update"}' \
            https://api.github.com/repos/nixpkgs-friendly/nixpkgs-friendly-overlay/dispatches
